#!/usr/bin/env node
/**
 * HOPLA — CSS bundle.
 *
 * The four files under assets/css are the editable source of truth. This
 * concatenates them in cascade order and strips comments and dead whitespace
 * into assets/css/hopla.css, which is what the pages actually link — one
 * request instead of four, which matters on a throttled mobile connection.
 *
 *   node scripts/build-css.js
 *
 * Re-run after editing any source file.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CSS = path.join(ROOT, 'assets/css');
const ORDER = ['tokens.css', 'base.css', 'components.css', 'sections.css'];
const OUT = path.join(CSS, 'hopla.css');

// Placeholders are control characters, which cannot occur in CSS source and
// survive whitespace collapsing. Bare digits would collide with real numbers
// in declarations and corrupt values.
const OPEN = '\u0001';
const CLOSE = '\u0002';

/**
 * Conservative minifier. It removes only what can never be significant:
 * comments, indentation and whitespace around structural punctuation. Quoted
 * strings and url() payloads — including data: URIs — are parked first so no
 * later rule can reach inside them.
 */
function minify(css) {
  const parked = [];
  const park = (m) => {
    parked.push(m);
    return `${OPEN}${parked.length - 1}${CLOSE}`;
  };

  const out = css
    // Comments go first: prose apostrophes ("the logo's arch") would
    // otherwise make the single-quote pattern below swallow whole sections.
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/url\([^)]*\)|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g, park)
    .replace(/\s+/g, ' ')                               // collapse whitespace
    .replace(/\s*([{};,>])\s*/g, '$1')                  // tighten punctuation
    .replace(/([\w)\]%]) ?: ?/g, '$1:')                 // `prop : v` → `prop:v`
    .replace(/;}/g, '}')                                // drop final semicolon
    .trim();

  return out.replace(
    new RegExp(`${OPEN}(\\d+)${CLOSE}`, 'g'),
    (_, i) => parked[Number(i)]
  );
}

/**
 * Guards against a minifier bug shipping silently: the bundle must retain
 * every brace, at-rule and custom property the sources declared.
 */
function verify(source, bundled) {
  const stripComments = (s) => s.replace(/\/\*[\s\S]*?\*\//g, '');
  const count = (s, re) => (s.match(re) || []).length;
  const checks = [
    ['opening braces', /\{/g],
    ['closing braces', /\}/g],
    ['at-rules', /@[a-z-]+/gi],
    ['custom properties', /--[\w-]+\s*:/g],
    ['data URIs', /data:image/g],
  ];
  const problems = [];
  for (const [label, re] of checks) {
    const a = count(stripComments(source), re);
    const b = count(bundled, re);
    if (a !== b) problems.push(`${label}: ${a} in source but ${b} in bundle`);
  }
  return problems;
}

const banner = `/*! HOPLA — generated by scripts/build-css.js. Edit ${ORDER.join(', ')}, not this file. */\n`;
const raw = ORDER.map((f) => fs.readFileSync(path.join(CSS, f), 'utf8')).join('\n');
const minified = minify(raw);

const problems = verify(raw, minified);
if (problems.length) {
  console.error('✗ bundle rejected — minifier changed the stylesheet:');
  for (const p of problems) console.error(`    ${p}`);
  process.exit(1);
}

fs.writeFileSync(OUT, banner + minified + '\n');

const before = Buffer.byteLength(raw);
const after = Buffer.byteLength(banner + minified);
console.log(
  `✓ hopla.css  ${ORDER.length} files  ${(before / 1024).toFixed(1)} kB → ` +
  `${(after / 1024).toFixed(1)} kB  (−${Math.round((1 - after / before) * 100)}%)`
);
